[package]
name = "learn_wgpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.11.2"
tokio = { version = "1.36.0", features = ["full"] }
wgpu = "0.19.1"
winit = "0.29.10"
